// import Providers from '@/redux/provider';
import './globals.css';
import { Inter } from 'next/font/google';
import Script from 'next/script';
import React, { ReactNode } from 'react';

// Assuming the Inter font is correctly linked in your project
const inter = Inter({ subsets: ['latin'] });

interface RootLayoutProps {
  children: ReactNode;
}

export const metadata = {
  title: 'ROS Dashboard SLAM',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Script src="https://code.createjs.com/1.0.0/createjs.min.js" strategy="beforeInteractive" />
      
      </head>
      <body className={inter.className} suppressHydrationWarning={true}>
        {/* <Providers> */}
          {children}
        {/* </Providers> */}
      </body>
    </html>
  );
}
